# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.ssh.username = "ansible"
  config.ssh.password = "root"

  config.vm.define "virtualbox" do |vb|
    vb.vm.hostname = "ansible-box-ubuntu2204"
    vb.vm.box = "file://../builds/ansible-box-ubuntu-2204.box"
    vb.vm.network :private_network, ip: "192.168.56.100"

    config.vm.provider :virtualbox do |vm|
      vm.memory = "4098"
      vm.cpus = "2"
    end
  end

  config.vm.provision "shell", inline: "echo Hello, World"
end